### ISSUE TITLE
Examples TODO

### ISSUE THREAD

**Issue by atbe** [thirdweb-dev/examples#1]
## Today:

- Splits
    - [x] Using a split contract https://thirdweb.com/portal/learn/code-examples#deploying-a-splits-module
    - [x] Changing the royalty recipient address for an existing module https://thirdweb.com/portal/learn/code-examples#changing-the-royalty-recipient-address-of-an-existing-module
- Drops
    - [x] Minting a batch https://thirdweb.com/portal/learn/code-examples#batch-lazy-mint-an-nft
- NFT Collection
    - [x] Minting an NFT https://thirdweb.com/portal/learn/code-examples#mint-an-nft
    - [ ] Confirm presence of NFT

Batch minting:
- [ ] Batch mint (bundle, pack, currency, drop)

## Later:

- Market
    - [ ] List an NFT on the marketplace
    - [ ] Buy an NFT on the marketplace
    - [ ] Use client wallet signer instance of SDK (@eabdelmoneim do you mean using a connected signer like metamask when using the sdk instead of a private key?)
- Currency
    - [ ] Create 1k custom tokens
    - [ ] Transfer token to another wallet
